// 2026 NFL Draft — Round 1 Pick Order
// Source: ESPN (espn.com/nfl/draft/rounds), April 2026
// Notes: Jets hold picks 2 & 16, Cowboys hold picks 12 & 20,
//        Browns hold picks 6 & 24, Chiefs hold picks 9 & 29, Dolphins hold picks 11 & 30

export const DRAFT_ORDER_2026 = [
  { pick: 1, team: 'Las Vegas Raiders', abbr: 'LV' },
  { pick: 2, team: 'New York Jets', abbr: 'NYJ' },
  { pick: 3, team: 'Arizona Cardinals', abbr: 'ARI' },
  { pick: 4, team: 'Tennessee Titans', abbr: 'TEN' },
  { pick: 5, team: 'New York Giants', abbr: 'NYG' },
  { pick: 6, team: 'Cleveland Browns', abbr: 'CLE' },
  { pick: 7, team: 'Washington Commanders', abbr: 'WAS' },
  { pick: 8, team: 'New Orleans Saints', abbr: 'NO' },
  { pick: 9, team: 'Kansas City Chiefs', abbr: 'KC' },
  { pick: 10, team: 'Cincinnati Bengals', abbr: 'CIN' },
  { pick: 11, team: 'Miami Dolphins', abbr: 'MIA' },
  { pick: 12, team: 'Dallas Cowboys', abbr: 'DAL' },
  { pick: 13, team: 'Los Angeles Rams', abbr: 'LAR' },
  { pick: 14, team: 'Baltimore Ravens', abbr: 'BAL' },
  { pick: 15, team: 'Tampa Bay Buccaneers', abbr: 'TB' },
  { pick: 16, team: 'New York Jets', abbr: 'NYJ' },
  { pick: 17, team: 'Detroit Lions', abbr: 'DET' },
  { pick: 18, team: 'Minnesota Vikings', abbr: 'MIN' },
  { pick: 19, team: 'Carolina Panthers', abbr: 'CAR' },
  { pick: 20, team: 'Dallas Cowboys', abbr: 'DAL' },
  { pick: 21, team: 'Pittsburgh Steelers', abbr: 'PIT' },
  { pick: 22, team: 'Los Angeles Chargers', abbr: 'LAC' },
  { pick: 23, team: 'Philadelphia Eagles', abbr: 'PHI' },
  { pick: 24, team: 'Cleveland Browns', abbr: 'CLE' },
  { pick: 25, team: 'Chicago Bears', abbr: 'CHI' },
  { pick: 26, team: 'Buffalo Bills', abbr: 'BUF' },
  { pick: 27, team: 'San Francisco 49ers', abbr: 'SF' },
  { pick: 28, team: 'Houston Texans', abbr: 'HOU' },
  { pick: 29, team: 'Kansas City Chiefs', abbr: 'KC' },
  { pick: 30, team: 'Miami Dolphins', abbr: 'MIA' },
  { pick: 31, team: 'New England Patriots', abbr: 'NE' },
  { pick: 32, team: 'Seattle Seahawks', abbr: 'SEA' },
];
